[versions]
mastodonk = "0.1-alpha10"

[libraries]
mastodonk-core = { module = "fr.outadoc.mastodonk:mastodonk-core", version.ref = "mastodonk" }
mastodonk-paging = { module = "fr.outadoc.mastodonk:mastodonk-paging", version.ref = "mastodonk" }
androidx-activity-compose = "androidx.activity:activity-compose:1.3.0-alpha03"
androidx-appcompat = "androidx.appcompat:appcompat:1.2.0"
androidx-core = "androidx.core:core-ktx:1.3.1"
junit = "junit:junit:4.13"
