name: Lint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  android-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Android Lint
      run: ./gradlew app-android:lintRelease

    - name: Parse Lint report
      uses: yutailang0119/action-android-lint@v2
      with:
        report-path: app-android/build/reports/lint-results*.xml
      continue-on-error: false
